### ISSUE TITLE
메인 탭 네이티브와 플러터간 통신

### ISSUE THREAD

**Issue by fell8000** [shicmts/flutter_sample_app#2]
### 개요

네이티브와 플러터간 통신을 설정하여 정보를 주고받으려합니다.

--------

### 작업사항

+ 로그인 화면 구성하기(전달할 정보 세팅)
+ 플러터 코드에 통신을 위한 코드 추가
+ 네이티브에 통신을 위한 코드 추가
+ 플러터에서 텍스트 입력받기
+ 입력받은 정보 안드로이드로 넣어 룸에서 저장

+ 룸에 있는 정보 플러터로 보내서 리스트 보여주기
+ 로컬로 푸시 보내기

**Comment by skrud9704** [comment]
작업완료로 이슈를 닫습니다.
