### ISSUE TITLE
[NEW] 차트 탭 추가

### ISSUE THREAD

**Issue by fell8000** [shicmts/flutter_sample_app#8]
## 개요
* 차트 탭을 추가하고 피드백 탭을 삭제하였습니다.
* 바이낸스 비트코인의 캔들 차트를 추가하려고 합니다.

## 작업사항
* AOS 작업
* iOS 작업
- 동일작업
* 피드백 탭 -> 차트 탭
* 바이낸스 api 연결
* 캔들 차트 한시간봉으로 설정

**Comment by skrud9704** [comment]
작업완료로 이슈를 닫습니다.
