### ISSUE TITLE
화면 구조 변경

### ISSUE THREAD

**Issue by fell8000** [shicmts/flutter_sample_app#9]
## 개요
* Drawer을 삭제 (기능 최소화)
* 탭4 추가(리스트뷰)

## 작업사항
* 로그인 텍스트 추가 및 조건 추가
* 웹뷰 -> 비트코인차트
* 탭4 추가
* 전체적인 구조 변경(Home탭으로 기능 통합)

**Comment by skrud9704** [comment]
작업완료로 이슈를 닫습니다.
